fix: Set extrinsic weight based on benchmarking
sygmaprotocol/sygma-substrate-pallets pull request #100
Opened 2023-04-26 14:40 UTC by tolak

## ❗️Breaking Change

Each pallet config now have a new item `WeightInfo` which should be configured as the `SygmaWeightInfo` object defined in the `weights.rs` file.

In this PR, we add benchmarking for each pallet, which is a tool to measure the weight coast of the pallet provided by Substrate.

The benchmarking is based on the runtime in `substrate-node/runtime/src/lib.rs`, basically what we have done is:

## Build with benchmark features enable

```sh
cargo build --release --features=runtime-benchmarks
```

## Run benchmarking for a specific pallet (for example: sygma-bridge)

```
./target/release/node-template benchmark pallet \
    --chain dev \
    --execution=wasm \
    --wasm-execution=compiled \
    --pallet sygma_bridge \
    --extrinsic "*" \
    --steps 50 \
    --repeat 20 \
    --output ./bridge/src/weights.rs
  ```
  
  ## Update weight info in extrinsic

For example the `deposit` function in sygma-bridge:
```
#[pallet::weight(<T as Config>::WeightInfo::deposit())]
pub fn deposit(
```

2023-05-02 12:46 UTC, MakMuftic commented
closes #89

2023-05-08 19:16 UTC, pesco requested changes
I see neither an upper limit imposed on the number of proposals in a call to `execute_proposal`, nor that the weight calculation takes the number of proposals into account dynamically. So I don't see how this fixes issue https://github.com/sygmaprotocol/sygma-substrate-pallets/issues/89.

2023-05-09 13:39 UTC, tolak commented
@pesco fixed

2023-05-09 16:00 UTC, pesco approved these changes

2023-05-10 07:49 UTC, mpetrun5 approved these changes

2023-05-10 07:55 UTC, merged